"""

PROBLEM 002 - Even Fibonacci Numbers

Written By: Yuanjie Li
Date: Jan 19, 2017

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

"""

def main():

  Output = 0
  FibArr = [1,1,2,3]

  while FibArr[2] < 4000000:
    if FibArr[2] % 2 == 0:
      Output += FibArr[2]

    FibArr[3] = FibArr[2] + FibArr[1]
    FibArr[0] = FibArr[1]
    FibArr[1] = FibArr[2]
    FibArr[2] = FibArr[3]

  print Output

if __name__ == "__main__":
  main()
