#coding=utf-8
"""
Written by: Yuanjie Li
Date: Oct 13, 2017

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

    1:  1
    3:  1,3
    6:  1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?

"""

import sys
sys.path.insert(0, '../utils')
import utils

# Tri Num with 2 divisors

def main():

    tri = 1
    num = 1
    num_divs = 1

    # Keep going until you find at least 500 divisors
    while num_divs <= 500:
        # Calculate next tri number
        tri += num
        num += 1

        # Get the number of divisors
        new_divs = len(utils.getDivs(tri))
        if new_divs > num_divs:
            num_divs = new_divs
            print("Best is now " + str(tri) + " with " + str(num_divs))

    print(tri)

if __name__ == "__main__":
  main()

